[build]
publish = "public_html"
command = "hugo --gc"

[context.production.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.72.0"

[context.branch-deploy]
command = "hugo --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.72.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#
# [[redirects]]
#  from = "https://salamandradevs.netlify.app"
#  to = "https://salamandradevs.site"
#  status = 301
#  force = true

[[headers]]
  # Enable CORS.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
