[build]
publish = "public_html"
command = "hugo --gc"

[context.production.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.startpoint]
command = "hugo --gc -b https://startpoint.salamandradevs.site"

[context.startpoint.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
  # Enable CORS.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
